/* Progressive enhancement; original operation handlers remain the single source of actions. */
(() => {
  const nav = document.querySelector('.operation-nav');
  const appearance=document.createElement('details');appearance.className='plot-appearance';appearance.innerHTML='<summary>Plot appearance · palette and smoothing</summary>';const appearanceControls=document.getElementById('vizSmoothing').closest('.row3');appearanceControls.before(appearance);appearance.append(appearanceControls);
  nav.insertAdjacentHTML('beforeend', '<div><label for="quickAction">Run from here</label><select id="quickAction"></select></div><button id="quickRun" type="button">Run selected</button><div><label for="resolutionLimit">My maximum scan points</label><input id="resolutionLimit" type="number" min="9" max="40401" value="10000"></div><a href="/FIRST_STEPS.html" target="_blank">First steps ↗</a>');
  const action = document.getElementById('quickAction'), run = document.getElementById('quickRun');
  function refreshActions() {
    const old = action.value;
    const buttons = [...document.querySelectorAll('main button[id]')].filter(b => !b.closest('[hidden]') && (/^run/i.test(b.id)||/^(calculate|find|fit|detect|adaptive|compute|validate)/i.test(b.textContent.trim())) && !/benchmark/i.test(b.id));
    action.replaceChildren(...buttons.map(b => {const o=document.createElement('option');o.value=b.id;o.textContent=b.textContent.trim();o.disabled=b.disabled;return o;}));
    if([...action.options].some(o=>o.value===old))action.value=old;
    run.disabled=!action.value || document.getElementById(action.value)?.disabled;
  }
  run.onclick=()=>document.getElementById(action.value)?.click();
  action.onchange=()=>{run.disabled=document.getElementById(action.value)?.disabled;};
  document.querySelector('.workspace-nav').addEventListener('click',()=>setTimeout(refreshActions,0));
  nav.addEventListener('change',()=>setTimeout(refreshActions,0));
  const observer=new MutationObserver(refreshActions);
  observer.observe(document.querySelector('main'),{subtree:true,attributes:true,attributeFilter:['hidden','disabled']});
  refreshActions();
  const stickySize=new ResizeObserver(()=>{const height=document.querySelector('.workspace-nav').getBoundingClientRect().height;nav.style.top=innerWidth>650?height+'px':'0';document.documentElement.style.setProperty('--study-top',(height+nav.getBoundingClientRect().height+12)+'px');});stickySize.observe(document.querySelector('.workspace-nav'));stickySize.observe(nav);
  const budgetNote=document.createElement('small');budgetNote.className='scan-estimate';nav.append(budgetNote);
  function estimateRun(){const id=action.value;let count=1,op='';const n=id=>Number(document.getElementById(id)?.value||1);if(id==='runScatteringMap'){count=n('mapLambdaPoints')*n('mapThetaPoints');op='angle_wavelength';}else if(id==='run'||id==='runTmmSpectrum'){count=n('points');op=id==='run'?'spectrum':'tmm';}else if(id==='runPolarizationMap'){count=n('polMapPoints')**2;op='polarization_kspace';}let seconds=null;try{seconds=Number(localStorage.getItem('timing:'+op))*count||null;}catch{}budgetNote.textContent=count>1?`${count.toLocaleString()} requested samples · ${seconds?'estimated '+Math.ceil(seconds)+' s from an earlier run':'time estimate after first completed samples'}`:'Run monitor shows elapsed time; solver stages without measurable work use an indeterminate bar.';}
  action.addEventListener('change',estimateRun);document.querySelector('main').addEventListener('input',estimateRun);estimateRun();

  const tray=document.createElement('div');tray.className='run-tray';tray.setAttribute('aria-live','polite');document.body.append(tray);
  const originalFetch=window.fetch.bind(window);
  const excluded=new Set(['materials','figure','import_material']);
  window.fetch=async function(input,options={}) {
    const url=String(input), operation=url.startsWith('/api/')?url.slice(5):'';
    if(options.method!=='POST'||!operation||excluded.has(operation)||operation.includes('/'))return originalFetch(input,options);
    let payload;try{payload=JSON.parse(options.body);}catch{return originalFetch(input,options);}
    if(operation==='vector_modes'&&document.getElementById('vmCoreShape')){payload.core_shape=document.getElementById('vmCoreShape').value;payload.sidewall_angle_deg=Number(document.getElementById('vmSidewall').value);options={...options,body:JSON.stringify(payload)};}
    const count=payload.wavelength_points&&payload.theta_points?payload.wavelength_points*payload.theta_points:operation.includes('kspace')?Number(payload.points||1)**2:Number(payload.points||payload.wavelength_points||1);
    const cap=Number(document.getElementById('resolutionLimit').value);
    if(!Number.isFinite(cap)||cap<9||cap>40401||count>cap)return new Response(JSON.stringify({error:`This run requests ${count} points. Adjust My maximum scan points (9–40401) or reduce the resolution.`}),{status:400});
    for(const old of [...tray.querySelectorAll('[data-finished]')].slice(0,-2))old.remove();
    const item=document.createElement('div');item.className='run-item';
    const title=document.createElement('strong');title.textContent=operation.replaceAll('_',' ');
    const cancel=document.createElement('button');cancel.textContent='Cancel';
    const bar=document.createElement('progress'),detail=document.createElement('small');
    item.append(cancel,title,bar,detail);tray.append(item);
    const started=performance.now();let jobId,finished=false;
    let estimate=null;try{estimate=Number(localStorage.getItem('timing:'+operation))*count||null;}catch{}
    const clock=setInterval(()=>{if(!jobId)detail.textContent=`Submitting · ${((performance.now()-started)/1000).toFixed(0)} s elapsed${estimate?' · prior-run estimate ~'+estimate.toFixed(0)+' s':''}`;},250);
    cancel.onclick=()=>{if(jobId){originalFetch('/api/cancel/'+jobId,{method:'POST'}).catch(()=>{});cancel.disabled=true;cancel.textContent='Stopping…';detail.textContent='Stops at the next solver checkpoint.';}};
    const abort=()=>cancel.onclick();options.signal?.addEventListener('abort',abort,{once:true});
    try{
      const response=await originalFetch(input,{...options,headers:{...options.headers,'X-Workbench-Job':'1'}});
      if(response.status!==202){finished=true;return response;}
      jobId=(await response.json()).job_id;
      for(;;){
        const poll=await originalFetch('/api/jobs/'+jobId);const job=await poll.json();
        if(!poll.ok)throw Error(job.error||'Run status unavailable');
        if(job.total){bar.max=job.total;bar.value=job.completed;}
        detail.textContent=`${job.stage} · ${job.elapsed_seconds.toFixed(0)} s elapsed${job.total?' · '+job.completed+'/'+job.total+' points':''}${job.remaining_seconds!==null?' · ~'+job.remaining_seconds.toFixed(0)+' s remaining':estimate?' · prior-run estimate ~'+estimate.toFixed(0)+' s':' · estimating after completed work'}`;
        if(['complete','failed','cancelled'].includes(job.status)){
          finished=true;item.dataset.finished='true';bar.max=1;bar.value=1;cancel.textContent='Dismiss';cancel.disabled=false;cancel.onclick=()=>item.remove();
          detail.textContent=`${job.status} · ${job.elapsed_seconds.toFixed(1)} s${job.result?.error?' · '+job.result.error:''}`;
          if(job.status==='complete')try{localStorage.setItem('timing:'+operation,String(job.elapsed_seconds/count));}catch{}
          if(job.result?.rows)setTimeout(()=>showFailedPoints(job.result.rows),100);
          if(operation==='vector_modes'&&job.status==='complete')setTimeout(()=>recordModeRun(job.result,payload),100);
          if(['tmm','spectrum'].includes(operation)&&job.status==='complete')setTimeout(()=>showTmmPhase(job.result,operation),100);
          if(operation==='dipole_ldos'&&job.status==='complete')setTimeout(()=>{const node=document.getElementById('ldosStatus');if(node)node.append(document.createTextNode(` · Collected Γ/Γ₀ = ${job.result.normalized_collected_decay_rate?.toPrecision(5)??'unavailable'}`));},100);
          return new Response(JSON.stringify(job.result),{status:job.response_status||200,headers:{'Content-Type':'application/json'}});
        }
        await new Promise(resolve=>setTimeout(resolve,650));
      }
    }catch(error){detail.textContent=error.message;cancel.textContent='Dismiss';cancel.onclick=()=>item.remove();throw error;}
    finally{clearInterval(clock);options.signal?.removeEventListener('abort',abort);if(finished&&!jobId)item.remove();refreshActions();}
  };
  function showFailedPoints(rows){
    document.getElementById('failedPointHelp')?.remove();
    const failed=rows.filter(r=>r.status&&r.status!=='converged');if(!failed.length)return;
    const panel=document.createElement('details');panel.id='failedPointHelp';panel.className='workbench-help';panel.open=true;
    const heading=document.createElement('summary');heading.textContent=`Resolve ${failed.length} failed spectral points`;panel.append(heading);
    const text=document.createElement('p');text.textContent='Open a point below, raise the Fourier budget and run Single wavelength. If a grazing cutoff is reported, shift wavelength or angle slightly. Recheck the geometry grid, then rerun the spectrum. Raw exploratory data remain available; figures require passing checks.';panel.append(text);
    for(const row of failed){const b=document.createElement('button');b.className='secondary';b.textContent=`λ ${row.wavelength_um} µm · ${row.status}`;b.onclick=()=>{document.getElementById('wavelength_um').value=row.wavelength_um;document.querySelector('.tab[data-tab="single"]').click();document.getElementById('run').scrollIntoView({block:'center'});};panel.append(b);}
    document.getElementById('quality').prepend(panel);
  }
  const legend=document.createElement('div');legend.className='material-legend';document.getElementById('structure').after(legend);
  function updateLegend(){legend.replaceChildren();const seen=new Set();for(const l of layerValues())for(const side of ['background','feature']){if(side==='feature'&&l.kind==='uniform')continue;const key=l[side+'_material'],n=l[side+'_n'],id=key==='dielectric'?key+n:key;if(seen.has(id))continue;seen.add(id);const label=document.createElement('span'),swatch=document.createElement('i');swatch.style.background=materialColor(key,n);label.append(swatch,document.createTextNode(key==='dielectric'?'Constant n='+n:key));legend.append(label);}}
  document.getElementById('layers').addEventListener('change',updateLegend);document.getElementById('preset').addEventListener('change',()=>setTimeout(updateLegend,0));updateLegend();
  const contrast=document.createElement('p');contrast.className='notice warn';contrast.hidden=true;document.getElementById('layers').after(contrast);function checkContrast(){const equal=layerValues().map((l,i)=>({l,i})).filter(({l})=>l.kind!=='uniform'&&l.background_material===l.feature_material&&(l.background_material!=='dielectric'||Number(l.background_n)===Number(l.feature_n)));contrast.hidden=!equal.length;contrast.textContent=equal.length?`Layer ${equal.map(({i})=>i+1).join(', ')} has identical background and feature material. It is optically uniform; choose different materials to create a grating.`:'';}document.getElementById('layers').addEventListener('change',checkContrast);checkContrast();
  const guideLink=document.createElement('p');guideLink.className='workbench-help';guideLink.innerHTML='<strong>Start with a worked example.</strong> <a href="/FIRST_STEPS.html" target="_blank">Open the illustrated first-use handbook</a> · literature benchmark, exact settings, expected results, and interpretation. Print or save as PDF from your browser.';
  document.querySelector('.tutorial-card')?.prepend(guideLink);
  const originalSweepPlot=drawSweep;drawSweep=function(result){originalSweepPlot(result);const c=document.getElementById('sweepPlot'),g=c.getContext('2d'),xs=result.x_values||result.rows.map(r=>r.x),ys=result.y_parameter?result.y_values:result.rows.map(r=>r.value).filter(Number.isFinite);if(!xs.length||!ys.length)return;const xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);g.fillStyle='#40576c';g.font='14px Segoe UI';for(let i=0;i<=4;i++){g.fillText((xmin+(xmax-xmin)*i/4).toPrecision(4),80+820*i/4,537);g.fillText((ymax-(ymax-ymin)*i/4).toPrecision(4),25,47+470*i/4);}c._rawData={type:'parameter_sweep',result};};
  const modeHistory=[];
  function recordModeRun(data,input){
    modeHistory.push({data,input});
    let panel=document.getElementById('modeRunHistory');if(!panel){panel=document.createElement('div');panel.id='modeRunHistory';document.getElementById('vmStatus').after(panel);}
    const table=document.createElement('table');table.innerHTML='<tr><th>Run</th><th>Actual grid</th><th>Requested mesh (µm)</th><th>Pads x/top/bottom (µm)</th><th>Mode 1 n_eff</th><th>Change</th></tr>';
    modeHistory.forEach((entry,i)=>{const row=table.insertRow();for(const text of [i+1,`${entry.data.mesh.nx} × ${entry.data.mesh.ny}`,entry.input.mesh_um,[entry.input.padding_x_um,entry.input.padding_top_um,entry.input.padding_bottom_um].join(' / '),entry.data.modes[0].n_eff.real.toFixed(7),i?(entry.data.modes[0].n_eff.real-modeHistory[i-1].data.modes[0].n_eff.real).toExponential(3):'baseline'])row.insertCell().textContent=text;});
    panel.replaceChildren(table);const note=document.createElement('p');note.className='hint';note.textContent='Compare field shapes before assigning mode identity. This history compares the first sorted eigenvalue; mesh and padding must be varied separately. Core electric fraction measures |E|² localization, not guided power.';panel.append(note);
  }
  function showTmmPhase(data,context="tmm"){
    let panel=document.getElementById(context+'PhasePanel');if(!panel){panel=document.createElement('details');panel.id=context+'PhasePanel';panel.innerHTML='<summary>Reflection and transmission phase</summary><p class="hint">Wrapped degrees of tangential electric amplitudes at the first/last interfaces; exp(−iωt). Phase is omitted at zero amplitude and for an incoherent unpolarized average.</p><canvas width="1100" height="450" class="plot"></canvas>';document.getElementById(context==='tmm'?'tmmStatus':'quality').after(panel);}
    if(data.phase_convention)panel.querySelector('p').textContent=data.phase_convention;
    const rows=data.rows||[{...data,wavelength_um:data.model.wavelength_um}],c=panel.querySelector('canvas');
    const series=['r_phase_deg','t_phase_deg'].map((key,i)=>({label:i?'Transmission phase':'Reflection phase',color:i?'#087d70':'#1768a5',x:rows.map(r=>r.wavelength_um),y:rows.map(r=>r[key]??NaN)}));
    if(!series.some(s=>s.y.some(Number.isFinite))){c.hidden=true;return;}c.hidden=false;const main=document.getElementById('plot');main.id='mainPowerPlot';c.id='plot';try{drawLines(series,'Vacuum wavelength (µm)','Wrapped phase (°)');}finally{c.id=context+'PhasePlot';main.id='plot';}c._rawData={series,phase_convention:data.phase_convention};scrollableChart(c);
  }
  // Phase requires complex amplitudes; never invent phase for R/T/A or LDOS.
  function phasePlot(canvas,values,description,axes={x0:0,x1:1,y0:0,y1:1,xlabel:'unit-cell coordinate u',ylabel:'unit-cell coordinate v',topDown:false}){
    const g=canvas.getContext('2d'),left=90,top=55,pw=canvas.width-230,ph=canvas.height-125;
    g.fillStyle='white';g.fillRect(0,0,canvas.width,canvas.height);const ny=values.length,nx=values[0].length,small=document.createElement('canvas');small.width=nx;small.height=ny;const im=small.getContext('2d').createImageData(nx,ny);
    for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const v=values[axes.topDown?y:ny-1-y][x],i=4*(y*nx+x);if(!Number.isFinite(v)){im.data.set([210,215,220,255],i);continue;}const f=Math.min(1,Math.abs(v)/180),p=Math.round(245*(1-f));im.data.set(v>=0?[230,p,p,255]:[p,p,230,255],i);}
    small.getContext('2d').putImageData(im,0,0);g.imageSmoothingEnabled=false;g.drawImage(small,left,top,pw,ph);g.strokeStyle='#234';g.strokeRect(left,top,pw,ph);g.fillStyle='#18344b';g.font='16px Segoe UI';g.fillText(description,20,28);g.fillText('−180° blue',left+pw+12,top+35);g.fillText('0° white',left+pw+12,top+65);g.fillText('+180° red',left+pw+12,top+95);g.fillText('Gray: undefined',left+pw+12,top+130);
    g.font='12px Segoe UI';for(let i=0;i<=4;i++){g.fillText((axes.x0+(axes.x1-axes.x0)*i/4).toPrecision(3),left+pw*i/4-12,top+ph+20);g.fillText((axes.y0+(axes.y1-axes.y0)*(axes.topDown?i/4:1-i/4)).toPrecision(3),left-50,top+ph*i/4+4);}g.fillText(axes.xlabel,left+pw/2-40,top+ph+42);g.save();g.translate(16,top+ph/2);g.rotate(-Math.PI/2);g.fillText(axes.ylabel,-45,0);g.restore();
    canvas._chart=null;canvas._researchHeat={values,nx,ny,left,top,pw,ph,...axes,label:description};installMapHover(canvas);canvas._rawData={quantity:description,phase_deg:values,axes};
  }
  for(const id of ['vmQuantity','fieldVariable','verticalVariable']){
    const select=document.getElementById(id);for(const name of ['Ex','Ey','Ez','Hx','Hy','Hz'])select.add(new Option(name+' phase (°)',name+'_phase_deg'));
    const previous=select.onchange;select.onchange=function(){if(!this.value.endsWith('_phase_deg'))return previous?.call(this);const values=id==='vmQuantity'?vectorModeData?.modes[Number(document.getElementById('vmMode').value)||0]?.fields[this.value]:id==='fieldVariable'?fieldData?.[this.value]:verticalData?.[this.value];if(values){let axes;if(id==='vmQuantity')axes={x0:vectorModeData.x_um[0],x1:vectorModeData.x_um.at(-1),y0:vectorModeData.y_um[0],y1:vectorModeData.y_um.at(-1),xlabel:'x (µm)',ylabel:'y (µm)'};if(id==='verticalVariable')axes={x0:0,x1:1,y0:verticalData.z_um[0],y1:verticalData.z_um.at(-1),xlabel:'position along primitive vector',ylabel:'z (µm)',topDown:true};const canvas=document.getElementById(id==='vmQuantity'?'vmPlot':'plot');phasePlot(canvas,values,this.selectedOptions[0].text,axes);if(id==='verticalVariable'){const h=canvas._researchHeat;drawVerticalStructureProfile(canvas.getContext('2d'),verticalData,h.left,h.top,h.pw,h.ph);}}};
  }
  const polSelect=document.getElementById('polMapQuantity');for(const name of ['Ep','Es'])polSelect.add(new Option(name+' phase (°)',name+'_phase_deg'));const oldPol=polSelect.onchange;polSelect.onchange=function(){if(!this.value.endsWith('_phase_deg'))return oldPol?.call(this);if(lastPolarizationMap){const d=lastPolarizationMap;phasePlot(document.getElementById('polarizationMapCanvas'),d.maps[this.value],this.selectedOptions[0].text+' · outgoing local p/s basis',{x0:d.u[0],x1:d.u.at(-1),y0:d.v[0],y1:d.v.at(-1),xlabel:'kx / (nᵢ k₀)',ylabel:'ky / (nᵢ k₀)'});}};
  const mapSelect=document.getElementById('mapQuantity');mapSelect.add(new Option('Specular reflection phase (°)','r_phase_deg'));mapSelect.add(new Option('Specular transmission phase (°)','t_phase_deg'));const oldScalar=drawScalarMap;drawScalarMap=function(data){if(!data.quantity.endsWith('_phase_deg'))return oldScalar(data);lastScatteringMap=data;const angle=data.kind==='angle_wavelength',x=angle?data.wavelength_um:data.u,y=angle?data.theta_deg:data.v;phasePlot(document.getElementById('scatteringMapCanvas'),data.values,data.quantity+' · coherent component; check phase convergence separately',{x0:x[0],x1:x.at(-1),y0:y[0],y1:y.at(-1),xlabel:angle?'Vacuum wavelength (µm)':'kx / (nᵢ k₀)',ylabel:angle?'Incidence angle (°)':'ky / (nᵢ k₀)'});};
  const branch=document.getElementById('runQBranches');if(branch){const link=document.createElement('button');link.type='button';link.className='secondary';link.textContent='Track several resonance branches →';link.onclick=()=>{showWorkspace('sweeps');branch.closest('details').open=true;branch.scrollIntoView({block:'center'});refreshActions();};document.getElementById('runMultiResonance')?.parentElement.append(link);if(!link.isConnected)document.getElementById('runResonance').parentElement.append(link);}
  const vectorRun=document.getElementById('runVectorMode');const vectorShape=document.createElement('div');vectorShape.className='row';vectorShape.innerHTML='<div><label for="vmCoreShape">Core cross-section</label><select id="vmCoreShape"><option value="rectangle">Rectangle</option><option value="trapezoid">Trapezoid</option><option value="ellipse">Ellipse</option></select></div><div><label for="vmSidewall">Sidewall angle (°)</label><input id="vmSidewall" type="number" min="20" max="90" value="90"></div>';vectorRun.closest('.card').querySelector('.actions')?.before(vectorShape);
  const refine=document.createElement('button');refine.id='runModeRefinement';refine.className='secondary';refine.textContent='Run mesh + padding comparison';vectorRun.after(refine);
  refine.onclick=async()=>{refine.disabled=true;const read=id=>Number(document.getElementById(id).value),input={wavelength_um:read('vmLambda'),core_width_um:read('vmWidth'),core_height_um:read('vmHeight'),core_n:read('vmCore'),substrate_n:read('vmSub'),cladding_n:read('vmClad'),padding_x_um:read('vmPadX'),padding_top_um:read('vmPadTop'),padding_bottom_um:read('vmPadBottom'),mesh_um:read('vmMesh'),modes:read('vmModes'),guess:read('vmGuess'),boundary:document.getElementById('vmBoundary').value,core_shape:document.getElementById('vmCoreShape').value,sidewall_angle_deg:read('vmSidewall')};try{for(const test of [input,{...input,mesh_um:input.mesh_um/2},{...input,padding_x_um:input.padding_x_um*1.25,padding_top_um:input.padding_top_um*1.25,padding_bottom_um:input.padding_bottom_um*1.25}]){const response=await fetch('/api/vector_modes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(test)});const result=await response.json();if(!response.ok)throw Error(result.error);vectorModeData=result;document.getElementById('vmMode').replaceChildren(...result.modes.map((m,i)=>new Option('Mode '+(i+1),i)));drawVectorMode();}document.getElementById('vmStatus').textContent='Three runs completed: baseline, half mesh at fixed padding, and larger padding at baseline mesh. Inspect mode identity and numerical changes below.';}catch(e){document.getElementById('vmStatus').textContent=e.message;}finally{refine.disabled=false;}};

  // Resonance evidence uses the same complex field payload as the vertical-field workspace.
  const resCase=document.getElementById('resFieldCase');
  if(resCase){
    const quantity=document.createElement('select');quantity.id='resFieldQuantity';
    for(const [value,label] of [['E2','Electric intensity |E|²'],['H2','Magnetic intensity |H|²'],['Ex_phase_deg','Eₓ phase (°)'],['Ey_phase_deg','Eᵧ phase (°)'],['Ez_phase_deg','Eᶻ phase (°)'],['Hx_phase_deg','Hₓ phase (°)'],['Hy_phase_deg','Hᵧ phase (°)'],['Hz_phase_deg','Hᶻ phase (°)']])quantity.add(new Option(label,value));
    const wrap=document.createElement('div');wrap.innerHTML='<label for="resFieldQuantity">Displayed resonance field</label>';wrap.append(quantity);resCase.parentElement.after(wrap);
    quantity.onchange=()=>{if(!resonanceFieldData)return;const item=resonanceFieldData.cases[Number(resCase.value)||0],key=quantity.value;if(key==='E2')return drawResonanceFieldCase();const values=item.field[key];if(!values)return;phasePlot(document.getElementById('resFieldCanvas'),values,quantity.selectedOptions[0].text+' · '+item.label,{x0:0,x1:1,y0:item.field.z_um[0],y1:item.field.z_um.at(-1),xlabel:item.field.plane==='xz'?'a₁ coordinate':'a₂ coordinate',ylabel:'z (µm; top interface = 0)',topDown:true});const h=document.getElementById('resFieldCanvas')._researchHeat;drawVerticalStructureProfile(document.getElementById('resFieldCanvas').getContext('2d'),item.field,h.left,h.top,h.pw,h.ph);};
    resCase.addEventListener('change',()=>quantity.dispatchEvent(new Event('change')));
  }

  // Compact long workspaces without hiding the calculation title.
  const compact=document.createElement('button');compact.type='button';compact.className='secondary';compact.textContent='Collapse result cards';
  compact.onclick=()=>{const cards=[...document.querySelectorAll('section .card')].filter(card=>!card.hidden);const collapse=cards.some(card=>!card.classList.contains('compact-collapsed'));for(const card of cards)card.classList.toggle('compact-collapsed',collapse);compact.textContent=collapse?'Expand result cards':'Collapse result cards';};
  nav.append(compact);
  for(const card of document.querySelectorAll('section .card')){const h=card.querySelector(':scope > h2');if(!h)continue;const toggle=document.createElement('button');toggle.type='button';toggle.className='card-toggle';toggle.title='Collapse or expand this card';toggle.textContent='▾';toggle.onclick=()=>{card.classList.toggle('compact-collapsed');toggle.textContent=card.classList.contains('compact-collapsed')?'▸':'▾';};h.prepend(toggle);}

  // Searchable control glossary assembled from visible labels plus curated physics guidance.
  const definitions={
    'Requested Fourier harmonics':'Controls the lateral Fourier basis. Increase until the observable and field pattern stop changing. Runtime and memory grow rapidly.',
    'Geometry grid per axis':'Samples material boundaries before Fourier factorization. Refine independently from the harmonic budget.',
    'Incident angle θ (°)':'Angle from the incident-side surface normal. Avoid an exact diffraction-order cutoff when convergence warnings report grazing propagation.',
    'Azimuth φ (°)':'Direction of the in-plane incident wavevector relative to primitive vector a₁.',
    'Points':'Number of actually solved samples. Display smoothing does not add physical resolution.',
    'Mesh step (µm)':'Finite-difference cell size. Repeat at a smaller value while holding the domain padding fixed.',
    'Maximum scan points':'Personal guardrail for total solved points. Raise it only after a coarse scan estimates cost and locates the feature.',
    'Noise σ':'Standard deviation assumed by the independent Gaussian likelihood. Estimate it from measurement repeats or a justified noise model.',
    'Bootstrap replicates':'Repeated residual resamples used to expose fit instability. Use at least 100 for a final interval when runtime allows.',
    'Refinement rounds':'Number of interval-narrowing passes. More rounds help only when every round still samples the linewidth.',
    'Points per round':'Spectral samples in each adaptive pass. A fitted linewidth needs several calculated points across its width.',
    'Odd grid points':'Centered k-space sampling. Odd counts include the origin exactly.',
    'Minimum channel power':'Masks normalized polarization where division by nearly zero outgoing power is unstable.',
    'Vertical grid points':'Samples the one-dimensional mode eigenproblem. Refine until n_eff and the field profile agree.',
    'Maximum modes':'Number of eigenpairs requested near the supplied index guess; extra modes increase solve cost and help identify crossings.',
    'NA':'Objective numerical aperture in the upper medium. The accepted half-angle is asin(NA/n).'
  };
  const help=document.createElement('dialog');help.id='parameterHelp';help.innerHTML='<form method="dialog" class="help-head"><h2>Search controls and numerical guidance</h2><button aria-label="Close">Close</button></form><input id="helpSearch" type="search" placeholder="Search wavelength, Fourier, mesh, Q, NA…"><div id="helpResults"></div><p><a href="/FIRST_STEPS.html" target="_blank">Open the complete worked guide ↗</a></p>';document.body.append(help);
  const helpButton=document.createElement('button');helpButton.type='button';helpButton.className='secondary';helpButton.textContent='Search help';nav.append(helpButton);
  function helpEntries(){const seen=new Set(),items=[];for(const label of document.querySelectorAll('label')){const name=label.textContent.trim();if(!name||seen.has(name))continue;seen.add(name);const control=label.htmlFor?document.getElementById(label.htmlFor):label.parentElement?.querySelector('input,select,textarea');const card=label.closest('.card');const range=control?.type==='number'?`Range ${control.min||'unbounded'} to ${control.max||'unbounded'}${control.step?' · step '+control.step:''}.`:'';const local=label.parentElement?.querySelector('.hint')?.textContent||'';items.push({name,section:card?.querySelector('h2')?.textContent.trim()||'General',text:definitions[name]||local||'Use the displayed units and repeat the calculation at higher numerical resolution before quoting a sensitive result.',range});}return items;}
  function renderHelp(){const q=document.getElementById('helpSearch').value.trim().toLowerCase(),items=helpEntries().filter(v=>(v.name+' '+v.section+' '+v.text).toLowerCase().includes(q)).slice(0,80),out=document.getElementById('helpResults');out.innerHTML=items.length?items.map(v=>`<article><h3>${v.name}</h3><small>${v.section}</small><p>${v.text} ${v.range}</p></article>`).join(''):'<p>No matching control. Try a physical quantity or solver name.</p>';}
  helpButton.onclick=()=>{renderHelp();help.showModal();setTimeout(()=>document.getElementById('helpSearch').focus(),0);};document.getElementById('helpSearch').oninput=renderHelp;

  // Durable run history survives a server restart; numerical result arrays remain in project exports.
  const historyButton=document.createElement('button');historyButton.type='button';historyButton.className='secondary';historyButton.textContent='Run history';nav.append(historyButton);
  const historyDialog=document.createElement('dialog');historyDialog.innerHTML='<form method="dialog" class="help-head"><h2>Recent calculations</h2><button>Close</button></form><div id="jobHistory">Loading…</div>';document.body.append(historyDialog);
  historyButton.onclick=async()=>{historyDialog.showModal();const out=document.getElementById('jobHistory');try{const response=await originalFetch('/api/job-history'),data=await response.json();out.innerHTML=data.jobs.length?'<table><tr><th>Operation</th><th>Status</th><th>Finished</th><th>Elapsed</th><th>Progress</th></tr>'+data.jobs.map(j=>`<tr><td>${j.operation||'calculation'}</td><td>${j.status}</td><td>${j.finished_at?new Date(j.finished_at*1000).toLocaleString():'active'}</td><td>${Number(j.elapsed_seconds||0).toFixed(1)} s</td><td>${j.total?j.completed+'/'+j.total:j.stage||'—'}</td></tr>`).join('')+'</table>':'<p>No recorded calculations yet.</p>';}catch(error){out.textContent=error.message;}};
  const bayesSigma=document.getElementById('bayesSigma');if(bayesSigma){const correlation=document.createElement('div');correlation.innerHTML='<label for="bayesCorrelation">AR(1) wavelength-noise correlation</label><input id="bayesCorrelation" type="number" min="-0.94" max="0.94" step="0.01" value="0"><p class="hint">Use zero for independent errors. Estimate nonzero correlation from repeated-measurement residuals rather than tuning it for a narrower interval.</p>';bayesSigma.parentElement.after(correlation);}
  const optimizerSeed=document.getElementById('optimizerSeed');if(optimizerSeed){const robust=document.createElement('div');robust.className='row';robust.innerHTML='<div><label for="optimizerRobustSamples">Fabrication samples / candidate</label><input id="optimizerRobustSamples" type="number" min="1" max="12" value="1"></div><div><label for="optimizerRobustWeight">Variability penalty</label><input id="optimizerRobustWeight" type="number" min="0" max="2" step="0.05" value="0.25"></div>';optimizerSeed.closest('.row3').after(robust);}
  const bandCard=document.getElementById('bandModeCanvas')?.closest('.card');if(bandCard){const zone=document.createElement('details');zone.innerHTML='<summary>Complete-gap screen over the full reciprocal cell</summary><p class="hint">The standard Γ–X–M–Γ path can miss a band extremum. This calculation samples one complete reciprocal primitive cell before reporting a candidate complete gap.</p><div class="row"><div><label for="fullZonePoints">Odd k points per reciprocal axis</label><input id="fullZonePoints" type="number" min="5" max="31" step="2" value="9"></div><div class="actions"><button id="runFullZone" class="primary">Screen complete gaps</button></div></div><p id="fullZoneStatus" class="notice">Start with 9 × 9, then repeat at 15 × 15 or finer.</p><div id="fullZoneReport"></div>';bandCard.append(zone);document.getElementById('runFullZone').onclick=async()=>{const button=document.getElementById('runFullZone'),note=document.getElementById('fullZoneStatus');button.disabled=true;note.textContent='Scanning the reciprocal primitive cell…';try{const response=await fetch('/api/full_zone_gaps',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:bandModel(),points:Number(document.getElementById('fullZonePoints').value)})}),data=await response.json();if(!response.ok)throw Error(data.error);note.className='notice '+(data.complete_sampled_gaps.length?'ok':'warn');note.textContent=`Solved ${data.grid_points_per_axis} × ${data.grid_points_per_axis} k points. ${data.complete_sampled_gaps.length} sampled complete polarization gap(s).`;document.getElementById('fullZoneReport').innerHTML=data.complete_sampled_gaps.length?'<table><tr><th>Polarization</th><th>Bands</th><th>a/λ interval</th><th>Relative width</th><th>λ interval (µm)</th></tr>'+data.complete_sampled_gaps.map(g=>`<tr><td>${g.polarization}</td><td>${g.between_bands.join('–')}</td><td>${g.lower_a_over_lambda.toFixed(5)}–${g.upper_a_over_lambda.toFixed(5)}</td><td>${(100*g.relative_width).toFixed(2)}%</td><td>${g.wavelength_um.map(v=>v.toFixed(5)).join('–')}</td></tr>`).join('')+'</table><p>'+data.warning+'</p>':'<p>No complete gap was found on this grid. A directional path gap may still exist.</p>';}catch(error){note.className='notice bad';note.textContent=error.message;}finally{button.disabled=false;}};}
  // Arbitrary binary periodic cells: assisted bitmap/CSV import plus brush editor.
  // The solver extrudes this two-material mask through the selected layer.
  const originalLayerObject=layerObject,originalAddLayer=addLayer;
  function bytesToBase64(bytes){let text='',chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)text+=String.fromCharCode(...bytes.subarray(i,i+chunk));return btoa(text)}
  function base64ToBytes(value){if(!value)return null;const text=atob(value),out=new Uint8Array(text.length);for(let i=0;i<text.length;i++)out[i]=text.charCodeAt(i);return out}
  function defaultMask(width,height){const out=new Uint8Array(width*height);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const u=(x+.5)/width-.5,v=(y+.5)/height-.5;if(u*u+v*v<.18*.18)out[y*width+x]=255}return out}
  // Stable, material-aware colors make the structure preview useful as a
  // geometry check.  Transparent materials remain visible by their outline.
  const fallbackMaterialColor=materialColor;
  const materialPreviewColors={
    air:'rgba(214,232,245,.16)', silica:'rgba(126,207,231,.48)', bk7:'rgba(134,188,224,.52)',
    n_bak4:'rgba(113,173,216,.55)', n_sf11:'rgba(90,142,190,.58)', caf2:'rgba(176,230,222,.46)',
    baf2:'rgba(157,216,222,.48)', mgf2:'rgba(194,227,226,.45)', lif:'rgba(201,232,215,.43)',
    kf:'rgba(213,231,231,.43)', nacl:'rgba(214,226,243,.46)', al2o3:'rgba(154,174,232,.60)',
    tio2:'rgba(126,112,198,.72)', silicon:'rgba(66,76,102,.88)', sin:'rgba(226,163,62,.78)',
    gold:'rgba(212,163,42,.94)', silver_rakic:'rgba(188,199,211,.94)', aluminum_rakic:'rgba(166,179,192,.94)',
    copper_rakic:'rgba(190,104,61,.94)', tdbc_pva_015:'rgba(182,70,113,.74)', pmma:'rgba(241,151,184,.48)',
    polycarbonate:'rgba(240,177,98,.52)', polystyrene:'rgba(107,184,161,.50)', zeonex:'rgba(119,197,184,.48)'
  };
  materialColor=function(key,n){
    if(key==='dielectric'){
      const index=Number(n)||1;
      if(Math.abs(index-1)<1e-6)return materialPreviewColors.air;
      const light=Math.max(34,Math.min(72,78-index*13));
      return `hsla(207 48% ${light}% / .68)`;
    }
    return materialPreviewColors[key]||fallbackMaterialColor(key,n);
  };
  if(typeof updateLegend==='function')updateLegend();
  function hydrateMaskLayer(box,data={}){
    if(box.querySelector('.mask-editor'))return;
    const select=box.querySelector('[data-key="kind"]');
    if(![...select.options].some(o=>o.value==='custom_mask'))select.add(new Option('Imported / drawn binary mask','custom_mask'),select.options.length-1);
    if(data.kind==='custom_mask')select.value='custom_mask';
    const width=Number(data.custom_mask_width)||64,height=Number(data.custom_mask_height)||64;
    const initial=data.custom_mask_base64?base64ToBytes(data.custom_mask_base64):defaultMask(width,height);
    const editor=document.createElement('details');
    editor.className='mask-editor';
    editor.innerHTML=`<summary>Draw or import the periodic unit cell</summary>
      <p class="hint">White pixels use Feature material; dark pixels use Background. Opposite edges repeat periodically. Draw directly or import a PNG, JPEG, SVG, or rectangular CSV of 0/1 values.</p>
      <div class="row"><div><label>Mask width (pixels)</label><input data-mask-role="width" type="number" min="8" max="256" value="${width}"></div><div><label>Mask height (pixels)</label><input data-mask-role="height" type="number" min="8" max="256" value="${height}"></div></div>
      <canvas width="512" height="512" class="mask-drawing-canvas"></canvas>
      <div class="row"><div><label>Geometry starter</label><select data-mask-role="starter"><option value="l">L resonator</option><option value="split-ring">Split ring</option><option value="ring">Annular ring</option><option value="chevron">Chevron</option><option value="grating">Parallel grating</option><option value="phc">Photonic-crystal disk array</option><option value="dose">Dose / test matrix</option></select></div><div style="align-self:end"><button type="button" class="secondary" data-mask-role="load-starter">Load starter</button></div></div>
      <div class="row3"><div><label>Drawing tool</label><select data-mask-role="tool"><option value="brush">Freehand brush</option><option value="line">Straight line</option><option value="rectangle">Rectangle</option><option value="ellipse">Ellipse</option></select></div><div><label>Paint action</label><select data-mask-role="brush"><option value="255">Draw feature</option><option value="0">Erase to background</option></select></div><div><label>Line / brush width (pixels)</label><input data-mask-role="size" type="number" min="1" max="64" value="2"></div></div>
      <div class="row"><div><label>Shape interior</label><select data-mask-role="shape-fill"><option value="filled">Filled</option><option value="outline">Outline only</option></select></div><div><label>Image threshold</label><input data-mask-role="threshold" type="range" min="0" max="255" value="128"></div></div>
      <div class="actions"><button type="button" class="secondary" data-mask-role="undo">Undo</button><button type="button" class="secondary" data-mask-role="redo">Redo</button><label class="secondary" style="cursor:pointer">Import image / CSV<input data-mask-role="file" type="file" accept="image/*,.csv,text/csv" hidden></label><button type="button" class="secondary" data-mask-role="export-csv">Export CSV</button><button type="button" class="secondary" data-mask-role="export-svg">Export SVG</button><button type="button" class="secondary" data-mask-role="invert">Invert</button><button type="button" class="secondary" data-mask-role="clear">Clear</button></div>
      <div class="row"><div><label>Fabrication screen: minimum width (µm)</label><input data-mask-role="minimum-width" type="number" min="0" step="any" value="0.05"></div><div><label>Minimum gap (µm)</label><input data-mask-role="minimum-gap" type="number" min="0" step="any" value="0.05"></div></div>
      <input type="hidden" data-key="custom_mask_width"><input type="hidden" data-key="custom_mask_height"><input type="hidden" data-key="custom_mask_base64">
      <p class="hint" data-mask-role="status"></p><p class="hint" data-mask-role="drc"></p>`;
    box.querySelector('.layer-actions').before(editor);
    let pixels=initial.length===width*height?initial:defaultMask(width,height),w=width,h=height;
    let canvas=editor.querySelector('canvas'),context=canvas.getContext('2d'),drawing=false,startPoint=null,lastPoint=null,previewBase=null;
    const undo=[],redo=[];
    const field=k=>editor.querySelector(`[data-mask-role="${k}"]`),hidden=k=>editor.querySelector(`[data-key="custom_mask_${k}"]`);
    const snapshot=()=>new Uint8Array(pixels);
    function pushUndo(){undo.push(snapshot());if(undo.length>30)undo.shift();redo.length=0;field('undo').disabled=false;field('redo').disabled=true}
    function downloadMask(blob,name){const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
    function circularRuns(values,target){
      const n=values.length;if(!n||values.every(v=>v===target))return values[0]===target?[n]:[];
      const first=values.findIndex(v=>v!==target),runs=[];let count=0;
      for(let step=1;step<=n;step++){const v=values[(first+step)%n];if(v===target)count++;else if(count){runs.push(count);count=0}}
      return runs;
    }
    function fabricationScreen(){
      const px=Number(document.getElementById('period_x_um')?.value||1)/w,py=Number(document.getElementById('period_y_um')?.value||1)/h;
      let minFeature=Infinity,minGap=Infinity;
      for(let y=0;y<h;y++){const row=Array.from(pixels.slice(y*w,(y+1)*w),v=>v>127);for(const run of circularRuns(row,true))minFeature=Math.min(minFeature,run*px);for(const run of circularRuns(row,false))minGap=Math.min(minGap,run*px)}
      for(let x=0;x<w;x++){const col=Array.from({length:h},(_,y)=>pixels[y*w+x]>127);for(const run of circularRuns(col,true))minFeature=Math.min(minFeature,run*py);for(const run of circularRuns(col,false))minGap=Math.min(minGap,run*py)}
      const requiredWidth=Math.max(0,Number(field('minimum-width').value)||0),requiredGap=Math.max(0,Number(field('minimum-gap').value)||0);
      const featureText=Number.isFinite(minFeature)?`${minFeature.toPrecision(4)} µm`:'none',gapText=Number.isFinite(minGap)?`${minGap.toPrecision(4)} µm`:'none';
      const pass=(!Number.isFinite(minFeature)||minFeature+1e-12>=requiredWidth)&&(!Number.isFinite(minGap)||minGap+1e-12>=requiredGap);
      field('drc').className=`hint ${pass?'drc-pass':'drc-warn'}`;
      field('drc').textContent=`Pixel pitch ${px.toPrecision(4)} × ${py.toPrecision(4)} µm. Smallest axis-aligned feature ${featureText}; gap ${gapText}. ${pass?'Screen passed.':'Below the entered fabrication limit.'} This is a periodic pixel-run screen, not a foundry DRC or proximity-effect calculation.`;
    }
    function draw(){
      const small=document.createElement('canvas');small.width=w;small.height=h;const c=small.getContext('2d'),image=c.createImageData(w,h);
      for(let i=0;i<pixels.length;i++){const v=pixels[i],p=4*i;image.data[p]=image.data[p+1]=image.data[p+2]=v;image.data[p+3]=255}
      c.putImageData(image,0,0);context.imageSmoothingEnabled=false;context.clearRect(0,0,canvas.width,canvas.height);context.drawImage(small,0,0,canvas.width,canvas.height);
      context.strokeStyle='rgba(34,75,112,.18)';context.lineWidth=1;
      for(let x=0;x<=w;x+=Math.max(1,Math.ceil(w/32))){const q=x/w*canvas.width;context.beginPath();context.moveTo(q,0);context.lineTo(q,canvas.height);context.stroke()}
      for(let y=0;y<=h;y+=Math.max(1,Math.ceil(h/32))){const q=y/h*canvas.height;context.beginPath();context.moveTo(0,q);context.lineTo(canvas.width,q);context.stroke()}
      field('status').textContent=`${w} × ${h}; ${(100*pixels.reduce((a,b)=>a+(b>127),0)/pixels.length).toFixed(1)}% feature fill.`;fabricationScreen();
    }
    function commit(){hidden('width').value=w;hidden('height').value=h;hidden('base64').value=bytesToBase64(pixels);draw();if(typeof renderStructure==='function')requestAnimationFrame(()=>renderStructure())}
    function resize(){
      const nw=Math.max(8,Math.min(256,Number(field('width').value)||64)),nh=Math.max(8,Math.min(256,Number(field('height').value)||64)),next=new Uint8Array(nw*nh);
      undo.length=0;redo.length=0;field('undo').disabled=true;field('redo').disabled=true;for(let y=0;y<nh;y++)for(let x=0;x<nw;x++)next[y*nw+x]=pixels[Math.min(h-1,Math.floor(y*h/nh))*w+Math.min(w-1,Math.floor(x*w/nw))];w=nw;h=nh;pixels=next;field('width').value=w;field('height').value=h;commit()
    }
    function point(event){const rect=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(w-1,Math.floor((event.clientX-rect.left)/rect.width*w))),y:Math.max(0,Math.min(h-1,Math.floor((event.clientY-rect.top)/rect.height*h)))}}
    function dot(x,y,value,size,target=pixels){const radius=Math.max(0,(size-1)/2);for(let yy=Math.floor(y-radius);yy<=Math.ceil(y+radius);yy++)for(let xx=Math.floor(x-radius);xx<=Math.ceil(x+radius);xx++)if(xx>=0&&xx<w&&yy>=0&&yy<h&&Math.hypot(xx-x,yy-y)<=radius+.55)target[yy*w+xx]=value}
    function line(a,b,value,size,target=pixels){const steps=Math.max(Math.abs(b.x-a.x),Math.abs(b.y-a.y),1);for(let i=0;i<=steps;i++)dot(Math.round(a.x+(b.x-a.x)*i/steps),Math.round(a.y+(b.y-a.y)*i/steps),value,size,target)}
    function shape(a,b,value,size,tool,filled,target=pixels){
      if(tool==='line'){line(a,b,value,size,target);return}
      const x0=Math.min(a.x,b.x),x1=Math.max(a.x,b.x),y0=Math.min(a.y,b.y),y1=Math.max(a.y,b.y);
      if(tool==='rectangle'){
        if(filled)for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++)target[y*w+x]=value;
        else{line({x:x0,y:y0},{x:x1,y:y0},value,size,target);line({x:x1,y:y0},{x:x1,y:y1},value,size,target);line({x:x1,y:y1},{x:x0,y:y1},value,size,target);line({x:x0,y:y1},{x:x0,y:y0},value,size,target)}return;
      }
      const cx=(x0+x1)/2,cy=(y0+y1)/2,rx=Math.max(.5,(x1-x0)/2),ry=Math.max(.5,(y1-y0)/2);
      if(filled){for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++)if(((x-cx)/rx)**2+((y-cy)/ry)**2<=1)target[y*w+x]=value}
      else{const count=Math.max(24,Math.ceil(2*Math.PI*Math.max(rx,ry)));let previous={x:Math.round(cx+rx),y:Math.round(cy)};for(let i=1;i<=count;i++){const q={x:Math.round(cx+rx*Math.cos(2*Math.PI*i/count)),y:Math.round(cy+ry*Math.sin(2*Math.PI*i/count))};line(previous,q,value,size,target);previous=q}}
    }
    function loadStarter(name){
      pushUndo();pixels.fill(0);const X=u=>Math.round(u*(w-1)),Y=v=>Math.round(v*(h-1)),paintRect=(x0,y0,x1,y1)=>{for(let y=Y(y0);y<=Y(y1);y++)for(let x=X(x0);x<=X(x1);x++)pixels[y*w+x]=255};
      if(name==='l'){paintRect(.20,.18,.34,.78);paintRect(.20,.64,.72,.78)}
      if(name==='ring'||name==='split-ring'){for(let y=0;y<h;y++)for(let x=0;x<w;x++){const dx=(x+.5)/w-.5,dy=(y+.5)/h-.5,r=Math.hypot(dx,dy),gap=name==='split-ring'&&dx>.18&&Math.abs(dy)<.09;if(r>.25&&r<.37&&!gap)pixels[y*w+x]=255}}
      if(name==='chevron'){line({x:X(.16),y:Y(.22)},{x:X(.50),y:Y(.70)},255,Math.max(2,Math.round(w*.10)));line({x:X(.84),y:Y(.22)},{x:X(.50),y:Y(.70)},255,Math.max(2,Math.round(w*.10)))}
      if(name==='grating')for(let i=0;i<5;i++)paintRect(.08+i*.19,.08,.15+i*.19,.92);
      if(name==='phc')for(let gy=0;gy<4;gy++)for(let gx=0;gx<4;gx++){const cx=.14+gx*.24,cy=.14+gy*.24;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(Math.hypot((x+.5)/w-cx,(y+.5)/h-cy)<.065)pixels[y*w+x]=255}
      if(name==='dose')for(let gy=0;gy<4;gy++)for(let gx=0;gx<4;gx++){const half=.025+.009*(gx+gy);paintRect(.14+gx*.24-half,.14+gy*.24-half,.14+gx*.24+half,.14+gy*.24+half)}
      commit();
    }
    field('width').onchange=resize;field('height').onchange=resize;
    field('load-starter').onclick=()=>loadStarter(field('starter').value);
    field('minimum-width').oninput=fabricationScreen;field('minimum-gap').oninput=fabricationScreen;
    field('invert').onclick=()=>{pushUndo();pixels=pixels.map(v=>255-v);commit()};
    field('clear').onclick=()=>{pushUndo();pixels.fill(0);commit()};
    field('undo').disabled=true;field('redo').disabled=true;
    field('undo').onclick=()=>{if(!undo.length)return;redo.push(snapshot());pixels=undo.pop();field('undo').disabled=!undo.length;field('redo').disabled=false;commit()};
    field('redo').onclick=()=>{if(!redo.length)return;undo.push(snapshot());pixels=redo.pop();field('redo').disabled=!redo.length;field('undo').disabled=false;commit()};
    canvas.onpointerdown=e=>{drawing=true;canvas.setPointerCapture(e.pointerId);startPoint=lastPoint=point(e);previewBase=snapshot();pushUndo();const value=Number(field('brush').value),size=Number(field('size').value)||1;if(field('tool').value==='brush')dot(startPoint.x,startPoint.y,value,size);draw()};
    canvas.onpointermove=e=>{if(!drawing)return;const current=point(e),tool=field('tool').value,value=Number(field('brush').value),size=Number(field('size').value)||1;if(tool==='brush')line(lastPoint,current,value,size);else{pixels=new Uint8Array(previewBase);shape(startPoint,current,value,size,tool,field('shape-fill').value==='filled')}lastPoint=current;draw()};
    canvas.onpointerup=()=>{if(!drawing)return;drawing=false;commit()};canvas.onpointercancel=()=>{drawing=false};
    field('export-csv').onclick=()=>{const csv=Array.from({length:h},(_,y)=>Array.from(pixels.slice(y*w,(y+1)*w),v=>v>127?1:0).join(',')).join('\n');downloadMask(new Blob([csv],{type:'text/csv'}),'periodic_mask.csv')};
    field('export-svg').onclick=()=>{const px=Number(document.getElementById('period_x_um')?.value||1)/w,py=Number(document.getElementById('period_y_um')?.value||1)/h,rects=[];for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(pixels[y*w+x]>127)rects.push(`<rect x="${x*px}" y="${y*py}" width="${px}" height="${py}"/>`);const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w*px} ${h*py}" width="${w*px/1000}mm" height="${h*py/1000}mm"><metadata>Coordinates are micrometres; physical width ${w*px} µm and height ${h*py} µm.</metadata><g fill="black">${rects.join('')}</g></svg>`;downloadMask(new Blob([svg],{type:'image/svg+xml'}),'periodic_mask.svg')};
    field('file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.name.toLowerCase().endsWith('.csv')||file.type==='text/csv'){const rows=(await file.text()).trim().split(/\r?\n/).map(row=>row.trim().split(/[;,\s]+/).filter(Boolean).map(Number));if(rows.length<8||rows.some(row=>row.length!==rows[0].length)||rows[0].length<8||rows.length>256||rows[0].length>256||rows.flat().some(v=>!Number.isFinite(v)))throw Error('CSV must be a rectangular 8–256 by 8–256 numeric matrix');h=rows.length;w=rows[0].length;pixels=Uint8Array.from(rows.flat(),v=>v>0?255:0)}else{const bitmap=await createImageBitmap(file),side=Math.max(bitmap.width,bitmap.height),scale=Math.min(1,256/side);w=Math.max(8,Math.round(bitmap.width*scale));h=Math.max(8,Math.round(bitmap.height*scale));const temp=document.createElement('canvas');temp.width=w;temp.height=h;const c=temp.getContext('2d');c.drawImage(bitmap,0,0,w,h);const rgba=c.getImageData(0,0,w,h).data,threshold=Number(field('threshold').value);pixels=new Uint8Array(w*h);for(let i=0;i<pixels.length;i++){const a=rgba[4*i+3]/255,gray=(.2126*rgba[4*i]+.7152*rgba[4*i+1]+.0722*rgba[4*i+2])*a;pixels[i]=gray>=threshold?255:0}}undo.length=0;redo.length=0;field('undo').disabled=true;field('redo').disabled=true;field('width').value=w;field('height').value=h;commit();select.value='custom_mask';editor.open=true;select.dispatchEvent(new Event('change',{bubbles:true}))}catch(error){field('status').textContent=error.message}finally{e.target.value=''}};
    commit();editor.hidden=select.value!=='custom_mask';
  }
  layerObject=function(box){const value=originalLayerObject(box),editor=box.querySelector('.mask-editor');if(editor){value.custom_mask_width=Number(editor.querySelector('[data-key="custom_mask_width"]').value);value.custom_mask_height=Number(editor.querySelector('[data-key="custom_mask_height"]').value);value.custom_mask_base64=editor.querySelector('[data-key="custom_mask_base64"]').value}return value};
  addLayer=function(data=defaults){originalAddLayer(data);const box=[...document.querySelectorAll('#layers .layer')].find(item=>!item.querySelector('.mask-editor'));if(box)hydrateMaskLayer(box,data);updateLayerControls()};
  document.querySelectorAll('#layers .layer').forEach(box=>hydrateMaskLayer(box));
  const baseStructureDetails=updateStructureDetails;updateStructureDetails=function(){baseStructureDetails();const items=document.querySelectorAll('#structureDetails li');layerValues().forEach((layer,index)=>{if(layer.kind!=='custom_mask'||!items[index])return;const bytes=base64ToBytes(layer.custom_mask_base64),fill=bytes?.length?100*bytes.reduce((sum,value)=>sum+(value>127),0)/bytes.length:0,background=layer.background_material==='dielectric'?`constant n=${layer.background_n}`:layer.background_material,feature=layer.feature_material==='dielectric'?`constant n=${layer.feature_n}`:layer.feature_material;items[index].textContent=`Layer ${index+1}: imported ${layer.custom_mask_width}×${layer.custom_mask_height} mask, ${Number(layer.thickness_um)} µm thick; ${background} background, ${feature} feature, ${fill.toFixed(1)}% feature fill.`})};updateStructureDetails();
  const baseUpdateLayerControls=updateLayerControls;updateLayerControls=function(){baseUpdateLayerControls();for(const box of document.querySelectorAll('#layers .layer')){if(!box.querySelector('.mask-editor'))hydrateMaskLayer(box);const custom=box.querySelector('[data-key="kind"]').value==='custom_mask';box.querySelector('.mask-editor').hidden=!custom;if(custom){box.querySelector('[data-key="fill_x"]').disabled=true;box.querySelector('[data-key="fill_y"]').disabled=true;box.querySelector('.shape-note').textContent='Imported binary periodic cell: white = feature material, dark = background. The mask is extruded through this layer.'}}};updateLayerControls();

  // Metasurface local-periodic phase library and radial flat-lens assignment.
  const metaCard=document.createElement('div');metaCard.className='card';metaCard.innerHTML=`<div class="eyebrow">Metasurface assistant</div><h2>Phase library and flat-lens assignment</h2><p class="hint">Sweep one unit-cell parameter at the selected wavelength, record the complex specular phase and power, then assign the closest cells to the ideal radial lens phase. This is a local periodic approximation, not a finite-lens propagation solve.</p><div class="row3"><div><label for="metaParameter">Library parameter</label><select id="metaParameter"><option value="layer.0.fill_x">Layer 1 width / radius</option><option value="layer.0.fill_y">Layer 1 height</option><option value="layer.0.thickness_um">Layer 1 thickness (µm)</option></select></div><div><label for="metaStart">Start</label><input id="metaStart" type="number" step="any" value="0.10"></div><div><label for="metaStop">Stop</label><input id="metaStop" type="number" step="any" value="0.45"></div></div><div class="row3"><div><label for="metaPoints">Library cells</label><input id="metaPoints" type="number" min="5" max="201" value="31"></div><div><label for="metaPort">Controlled port</label><select id="metaPort"><option value="transmitted">Transmission</option><option value="reflected">Reflection</option></select></div><div><label for="metaMinimumPower">Minimum specular power</label><input id="metaMinimumPower" type="number" min="0" max="1" step="any" value="0.2"></div></div><div class="row3"><div><label for="metaRadius">Lens radius (µm)</label><input id="metaRadius" type="number" min="0" step="any" value="25"></div><div><label for="metaFocal">Focal length (µm)</label><input id="metaFocal" type="number" min="0" step="any" value="50"></div><div><label for="metaRadialPoints">Radial samples</label><input id="metaRadialPoints" type="number" min="3" max="2001" value="101"></div></div><div class="actions"><button id="runMetasurface" class="primary">Build library and assign lens</button><button id="exportMetasurface" class="secondary" disabled>Export JSON + radial CSV</button></div><p id="metaStatus" class="notice">Use normal incidence and coherent s or p polarization. Start with a low-NA lens and verify phase coverage before trusting an assignment.</p><canvas id="metaPlot" class="plot" width="1100" height="540"></canvas><div id="metaReport"></div><p><a href="/METASURFACE_GUIDE.html" target="_blank">Open the metasurface and application-driven design tutorial ↗</a></p>`;document.querySelector('section').append(metaCard);let metaResult=null;
  function drawMeta(data){const c=document.getElementById('metaPlot'),g=c.getContext('2d'),p={l:85,r:45,t:35,b:70},rows=data.library.filter(r=>r.phase_deg!==null),xmin=Math.min(...rows.map(r=>r.parameter)),xmax=Math.max(...rows.map(r=>r.parameter)),X=x=>p.l+(x-xmin)/(xmax-xmin)*(c.width-p.l-p.r),Y=y=>p.t+(180-y)/360*(c.height-p.t-p.b);g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#d6e1ed';for(let y=-180;y<=180;y+=90){g.beginPath();g.moveTo(p.l,Y(y));g.lineTo(c.width-p.r,Y(y));g.stroke();g.fillStyle='#52657b';g.fillText(y+'°',35,Y(y)+4)}g.strokeStyle='#1768a5';g.lineWidth=2.5;g.beginPath();rows.forEach((r,i)=>i?g.lineTo(X(r.parameter),Y(r.phase_deg)):g.moveTo(X(r.parameter),Y(r.phase_deg)));g.stroke();g.fillStyle='#263b52';g.font='16px Segoe UI';g.fillText(data.parameter_label,p.l+(c.width-p.l-p.r)/2-70,c.height-20);g.fillText('Wrapped specular phase',p.l,p.t-12);c._rawData={type:'metasurface_phase_library',result:data}}
  document.getElementById('runMetasurface').onclick=async()=>{const button=document.getElementById('runMetasurface'),note=document.getElementById('metaStatus');button.disabled=true;note.className='notice';note.textContent='Solving periodic library cells and assigning radial phase…';try{const payload={model:model(),parameter:document.getElementById('metaParameter').value,start:Number(document.getElementById('metaStart').value),stop:Number(document.getElementById('metaStop').value),points:Number(document.getElementById('metaPoints').value),port:document.getElementById('metaPort').value,lens_radius_um:Number(document.getElementById('metaRadius').value),focal_length_um:Number(document.getElementById('metaFocal').value),radial_points:Number(document.getElementById('metaRadialPoints').value),minimum_power:Number(document.getElementById('metaMinimumPower').value)},response=await fetch('/api/metasurface_phase_library',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw Error(data.error);metaResult=data;drawMeta(data);note.className='notice '+(data.maximum_phase_gap_deg<90&&data.rms_phase_error_deg<25?'ok':'warn');note.textContent=`Library solved. NA ${data.numerical_aperture.toFixed(3)}; largest phase gap ${data.maximum_phase_gap_deg.toFixed(1)}°; assigned RMS phase error ${data.rms_phase_error_deg.toFixed(1)}°.`;document.getElementById('metaReport').innerHTML=`<table><tr><th>Usable goal</th><th>Result</th></tr><tr><td>Mean selected specular power</td><td>${data.mean_selected_power.toFixed(4)}</td></tr><tr><td>Minimum selected power</td><td>${data.minimum_selected_power.toFixed(4)}</td></tr><tr><td>Global phase offset</td><td>${data.global_phase_offset_deg.toFixed(2)}°</td></tr></table><p class="hint">${data.scope} ${data.validation}</p>`;document.getElementById('exportMetasurface').disabled=false}catch(error){note.className='notice bad';note.textContent=error.message}finally{button.disabled=false}};
  document.getElementById('exportMetasurface').onclick=()=>{if(!metaResult)return;download(new Blob([JSON.stringify(metaResult,null,2)],{type:'application/json'}),'metasurface_phase_library.json');const columns=['radius_um','target_phase_deg','global_offset_deg','parameter','library_phase_deg','phase_error_deg','power'],csv=[columns.join(','),...metaResult.layout.map(row=>columns.map(k=>row[k]).join(','))].join('\n');download(new Blob([csv],{type:'text/csv'}),'flat_lens_radial_assignment.csv')};

  // Spectral metrics for ring/knot measurements; no curved 3D field claim.
  const knotCard=document.createElement('div');knotCard.className='card';knotCard.innerHTML=`<div class="eyebrow">Measured resonator assistant</div><h2>Ring and microfiber-knot spectral metrics</h2><p class="hint">Convert a measured resonance and round-trip path into loaded Q, FSR, finesse, photon lifetime, and circulation estimates. This does not solve the finite curved knot geometry.</p><div class="row3"><div><label for="knotLambda">Center λ (µm)</label><input id="knotLambda" type="number" step="any" value="1.55"></div><div><label for="knotLinewidth">Linewidth Δλ (µm)</label><input id="knotLinewidth" type="number" step="any" value="0.000001"></div><div><label for="knotNg">Group index</label><input id="knotNg" type="number" step="any" value="1.45"></div></div><div class="row3"><div><label for="knotLength">Round-trip length (µm)</label><input id="knotLength" type="number" step="any" value="3141.59"></div><div><label for="knotFsr">Measured FSR (µm; optional)</label><input id="knotFsr" type="number" step="any"></div><div><label for="knotTmin">On-resonance T minimum (optional)</label><input id="knotTmin" type="number" min="0" max="1" step="any"></div></div><div class="actions"><button id="runKnotMetrics" class="primary">Calculate resonator metrics</button></div><p id="knotStatus" class="notice">For a circular loop, round-trip length is πD. A knot needs its actual optical path, including both sub-knot paths and coupling region.</p><div id="knotReport"></div>`;document.querySelector('section').append(knotCard);
  document.getElementById('runKnotMetrics').onclick=async()=>{const note=document.getElementById('knotStatus');try{const optional=id=>document.getElementById(id).value.trim()===''?null:Number(document.getElementById(id).value),response=await fetch('/api/resonator_metrics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({wavelength_um:Number(document.getElementById('knotLambda').value),linewidth_um:Number(document.getElementById('knotLinewidth').value),group_index:Number(document.getElementById('knotNg').value),round_trip_length_um:Number(document.getElementById('knotLength').value),measured_fsr_um:optional('knotFsr'),transmission_minimum:optional('knotTmin')})}),data=await response.json();if(!response.ok)throw Error(data.error);note.className='notice ok';note.textContent='Metrics calculated from the supplied spectral and path-length quantities.';document.getElementById('knotReport').innerHTML=`<div class="metrics"><div class="metric"><span>Loaded Q</span><strong>${data.loaded_q.toPrecision(6)}</strong></div><div class="metric"><span>Finesse</span><strong>${data.finesse.toPrecision(5)}</strong></div><div class="metric"><span>Photon lifetime</span><strong>${(data.photon_lifetime_s*1e9).toPrecision(5)} ns</strong></div></div><table><tr><th>Quantity</th><th>Value</th></tr><tr><td>Estimated FSR</td><td>${data.estimated_fsr_um.toExponential(5)} µm</td></tr><tr><td>Lifetime round trips</td><td>${data.lifetime_round_trips.toPrecision(6)}</td></tr><tr><td>Equivalent circular diameter</td><td>${data.equivalent_ring_diameter_um.toPrecision(7)} µm</td></tr></table>${data.coupling_candidates?'<h3>Two coupling branches</h3><table><tr><th>Branch</th><th>Intrinsic Q</th><th>Coupling Q</th></tr>'+data.coupling_candidates.map(x=>`<tr><td>${x.branch}</td><td>${x.intrinsic_q.toPrecision(6)}</td><td>${x.coupling_q.toPrecision(6)}</td></tr>`).join('')+'</table><p class="hint">'+data.coupling_note+'</p>':''}<p class="hint">${data.scope}</p>`}catch(error){note.className='notice bad';note.textContent=error.message}};
  tutorialCard.insertAdjacentHTML('beforeend','<h3>Arbitrary cells, metasurfaces, and application-first design</h3><p>Import or draw a binary periodic cell, build a complex phase library, assign a flat lens, connect absorption/Q/BIC/gap/phase targets to applications, and distinguish a periodic cell from a finite microfiber-knot model in the <a href="/METASURFACE_GUIDE.html" target="_blank">metasurface and arbitrary-geometry guide ↗</a>.</p>');
  const overviewRender=renderStructure;
  function maskCanvas(layer,color){
    const w=Number(layer.custom_mask_width),h=Number(layer.custom_mask_height),bytes=base64ToBytes(layer.custom_mask_base64);
    if(!w||!h||!bytes||bytes.length!==w*h)return null;
    const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;
    const ctx=canvas.getContext('2d'),image=ctx.createImageData(w,h),probe=document.createElement('canvas').getContext('2d');
    probe.fillStyle=color;probe.fillRect(0,0,1,1);const rgb=probe.getImageData(0,0,1,1).data;
    const feature=(x,y)=>bytes[((y+h)%h)*w+(x+w)%w]>127;
    for(let y=0;y<h;y++)for(let x=0;x<w;x++){
      if(!feature(x,y))continue;
      const edge=!feature(x-1,y)||!feature(x+1,y)||!feature(x,y-1)||!feature(x,y+1),p=4*(y*w+x);
      image.data[p]=edge?Math.max(0,rgb[0]*.42):rgb[0];image.data[p+1]=edge?Math.max(0,rgb[1]*.42):rgb[1];image.data[p+2]=edge?Math.max(0,rgb[2]*.42):rgb[2];image.data[p+3]=edge?255:232;
    }
    ctx.putImageData(image,0,0);return canvas;
  }
  function drawImportedMasks(){const c=document.getElementById('structure'),g=c.getContext('2d'),layers=layerValues();if(!layers.some(layer=>layer.kind==='custom_mask'))return;const heights=layers.map(layer=>Math.max(26,Math.min(70,Number(layer.thickness_um)*170))),scale=Math.min(1,245/heights.reduce((a,b)=>a+b,0));for(let i=0;i<heights.length;i++)heights[i]*=scale;const cellAngle=number('lattice_angle_deg')*Math.PI/180,viewAngle=structureView.azimuth*Math.PI/180,elevation=structureView.elevation*Math.PI/180,p=(x,y,z)=>{const X=x+Math.cos(cellAngle)*y,Y=Math.sin(cellAngle)*y,cx=(1+Math.cos(cellAngle))/2,cy=Math.sin(cellAngle)/2,dx=X-cx,dy=Y-cy,xr=Math.cos(viewAngle)*dx-Math.sin(viewAngle)*dy,yr=Math.sin(viewAngle)*dx+Math.cos(viewAngle)*dy,v=structureView.zoom;return[390+v*300*xr,285+v*(180*Math.sin(elevation)*yr-Math.cos(elevation)*z)]};let z=0;for(let i=layers.length-1;i>=0;i--){const layer=layers[i],z1=z+heights[i];if(layer.kind==='custom_mask'){const bitmap=maskCanvas(layer,materialColor(layer.feature_material,layer.feature_n));if(bitmap){const p00=p(0,0,z1+.6),p10=p(1,0,z1+.6),p01=p(0,1,z1+.6);g.save();g.imageSmoothingEnabled=false;g.globalAlpha=.96;g.setTransform((p10[0]-p00[0])/bitmap.width,(p10[1]-p00[1])/bitmap.width,(p01[0]-p00[0])/bitmap.height,(p01[1]-p00[1])/bitmap.height,p00[0],p00[1]);g.drawImage(bitmap,0,0);g.restore()}}z=z1}const selected=Math.min(layers.length-1,Math.max(0,Number(document.getElementById('previewLayer')?.value||1)-1)),layer=layers[selected];if(layer?.kind==='custom_mask'){const bitmap=maskCanvas(layer,materialColor(layer.feature_material,layer.feature_n));if(bitmap){g.save();g.imageSmoothingEnabled=false;g.drawImage(bitmap,770,135,180,180);g.restore()}}document.getElementById('structureCaption').textContent+=' Imported masks are rendered from the exact saved pixels; their vertical sidewalls remain a schematic extrusion.'}
  renderStructure=function(){overviewRender();drawImportedMasks()};renderStructure();
  const priorShowWorkspace=showWorkspace;showWorkspace=function(name){priorShowWorkspace(name);metaCard.hidden=name!=='sweeps';knotCard.hidden=name!=='cavity';refreshOperationNavigator(name)};metaCard.hidden=activeWorkspace!=='sweeps';knotCard.hidden=activeWorkspace!=='cavity';
  refreshActions();
})();
